### ISSUE TITLE
Missing completed tasks?

### ISSUE THREAD

**Issue by Tulipan121** [yutannihilation/wunderlistr#4]
Dear Yutan,

I really like your project on accessing Wunderlist through R.

But I don't know how to get / see completed tasks. When I run wndr_get_task function in an list id, it only shows me uncompleted tasks.

Any suggestions? Maybe a small tweek of the code?

My suggestion would also be to include a wndr_get_json function, where one could get all info in one file...

Keep up the great work and all the best to you!

Blaz

**Comment by yutannihilation** [comment]
Thanks for using my package!

Unfortunately, I no longer have a Wunderlist account now, but I guess `completed = TRUE` should work. Have you tried?

``` r
wndr_get_task(list_id = "...", completed = TRUE)
```

**Comment by Tulipan121** [comment]
But of course. Obviously. The solution seems so easy after three hours of sleep. :)

#I_am_a_noob

Thank you!

**Comment by yutannihilation** [comment]
Haha, sleep well! Thanks for confirming!!!
